version: '2'

## ISLE Localdomain Docker-compose.  
## 
## This is generic docker-compose that when will load a complete Islandora Stack ready to test.
## You do not need to anything here!
##
## How to run:  `docker-compose up -d` 
## What you're watching: Docker is orchestrating our images, and running them for us!
## 
## The last step is to instantiate your Islandora ISLE.LOCALDOMAIN site.  Please copy and paste this into terminal:
## docker exec -it isle-apache-ld bash /tmp/isle_drupal_build_tools/apache_provision.sh 
##
## Visit http://localhost

### Stop editing here if you want to try the Islandora ISLE default installation. You are not required to edit anything below.
services:
  mysql:
    image: islandoracollabgroup/isle-mysql:latest
    container_name: isle-mysql-ld
    environment:
      - MYSQL_ROOT_PASSWORD=ild_mysqlrt_2018
    networks:
      - isle-internal
    ports:
      - "3306:3306"
    volumes:
      - db-data-ld:/var/lib/mysql
      - ./data/mysql/log:/var/log/mysql

  fedora:
    image: islandoracollabgroup/isle-fedora:latest
    container_name: isle-fedora-ld
    networks:
      - isle-internal
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - mysql
      - solr
    volumes:
      - fed-data-ld:/usr/local/fedora/data
      - ./data/fedora/log/fedora:/usr/local/fedora/server/logs
      - ./data/fedora/log/tomcat:/usr/local/tomcat/logs

  solr:
    image: islandoracollabgroup/isle-solr:latest
    container_name: isle-solr-ld
    networks:
      - isle-internal
    ports:
      - "8091:8080"
    tty: true
    depends_on:
      - mysql
    volumes:
      - solr-data-ld:/usr/local/solr/collection1/data
      - ./data/solr/logs:/usr/local/tomcat/logs

  apache:
    image: islandoracollabgroup/isle-apache:latest
    container_name: isle-apache-ld
    networks:
      isle-internal:
        aliases:
          - isle.localdomain
    tty: true
    depends_on:
      - mysql
      - fedora
      - solr
    volumes:
      - apache-data-ld:/var/www/html
      - ./data/apache/log/apache:/var/log/apache2

  proxy:
    image: islandoracollabgroup/isle-proxy:latest
    container_name: isle-proxy
    networks:
      isle-internal:
      isle-external:
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mysql
      - fedora
      - solr
      - apache


# Defined networks
networks:
  isle-internal:
  isle-external:

volumes:
  db-data-ld:
  fed-data-ld:
  solr-data-ld:
  apache-data-ld:
